zlanguage: go
dist: trusty
go_import_path: github.com/readhelper/libaudit-go
sudo: required
notifications:
    email: false
go:
    - 1.8
before_install:
    - sudo apt-get -qq update
    - sudo apt-get install -y auditd
    - go get -v github.com/lunixbochs/struc

#install:
#  - go get -v ./...

script:
    - sudo service auditd stop
    - make test
